#!/usr/bin/env python3

python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type tsc-lstm --depth 2 --epochs 5000 --batch_size 128 --test_batch_size 128 --save_best_model --no_overwrite --seed 0 --expt_name 2-lstm-crop-noise-0.3-epoch-5000-dac-learning-epoch-40-lr-0.001-noisy_val-iter1 --iteration 1 --loss_fn dac_loss --noise_percentage 0.3 --lr 0.001 --learn_epochs 40 --output_path results/crop/
python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type tsc-lstm --depth 2 --epochs 5000 --batch_size 128 --test_batch_size 128 --save_best_model --no_overwrite --seed 0 --expt_name 2-lstm-crop-noise-0.3-epoch-5000-dac-learning-epoch-40-lr-0.001-noisy_val-iter2 --iteration 2 --loss_fn dac_loss --noise_percentage 0.3 --lr 0.001 --learn_epochs 40 --output_path results/crop/
python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type tsc-lstm --depth 2 --epochs 5000 --batch_size 128 --test_batch_size 128 --save_best_model --no_overwrite --seed 0 --expt_name 2-lstm-crop-noise-0.3-epoch-5000-dac-learning-epoch-40-lr-0.001-noisy_val-iter3 --iteration 3 --loss_fn dac_loss --noise_percentage 0.3 --lr 0.001 --learn_epochs 40 --output_path results/crop/
python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type tsc-lstm --depth 2 --epochs 5000 --batch_size 128 --test_batch_size 128 --save_best_model --no_overwrite --seed 0 --expt_name 2-lstm-crop-noise-0.3-epoch-5000-dac-learning-epoch-40-lr-0.001-noisy_val-iter4 --iteration 4 --loss_fn dac_loss --noise_percentage 0.3 --lr 0.001 --learn_epochs 40 --output_path results/crop/
python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type tsc-lstm --depth 2 --epochs 5000 --batch_size 128 --test_batch_size 128 --save_best_model --no_overwrite --seed 0 --expt_name 2-lstm-crop-noise-0.3-epoch-5000-dac-learning-epoch-40-lr-0.001-noisy_val-iter5 --iteration 5 --loss_fn dac_loss --noise_percentage 0.3 --lr 0.001 --learn_epochs 40 --output_path results/crop/


python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type tsc-lstm --depth 2 --epochs 5000 --batch_size 128 --test_batch_size 128 --save_best_model --no_overwrite --seed 0 --expt_name 2-lstm-crop-noise-0.3-epoch-5000-dac-learning-epoch-40-lr-0.001-noisy_val-sgd-iter2 --iteration 2 --loss_fn dac_loss --noise_percentage 0.3 --lr 0.001 --learn_epochs 40 --output_path results/crop/
python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type tsc-lstm --depth 2 --epochs 5000 --batch_size 128 --test_batch_size 128 --save_best_model --no_overwrite --seed 0 --expt_name 2-lstm-crop-noise-0.5-epoch-5000-dac-learning-epoch-100-lr-0.001-noisy_val-updated-1-iter2 --iteration 2 --loss_fn dac_loss --noise_percentage 0.5 --lr 0.001 --learn_epochs 100 --output_path results/crop/

# learning rate 0.2^1 till 1000 then 0.2^2
python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type tsc-lstm --depth 2 --epochs 5000 --batch_size 128 --test_batch_size 128 --save_best_model --no_overwrite --seed 0 --expt_name 2-lstm-crop-noise-0.75-epoch-5000-dac-learning-epoch-400-lr-0.001-noisy_val-iter2 --iteration 2 --loss_fn dac_loss --noise_percentage 0.75 --lr 0.001 --learn_epochs 400 --output_path results/crop/

python3 tsc-train.py --datadir data/UCRArchive_2018 --dataset ucr-archive --nesterov --net_type inception_simple --depth 2 --epochs 400 --batch_size 64 --test_batch_size 64 --save_best_model --no_overwrite --seed 0 --expt_name inception-simple-crop-noise-0.5-epoch-400-dac-learning-epoch-10-lr-0.01-noisy_val-iter3 --iteration 3  --loss_fn dac_loss --noise_percentage 0.5  --lr 0.01 --learn_epochs 10 --output_path results/crop --load_epochs 186 --load_checkpoint results/crop/inception-simple_expt_name_inception-simple-crop-noise-0.5-epoch-400-dac-learning-epoch-10-lr-0.01-noisy_val-iter3_epoch_186.t7